import React, { useCallback, useEffect, useMemo, useState } from 'react'

const API = 'http://localhost:8080/api'
async function api(path, options = {}) {
  const response = await fetch(`${API}${path}`, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options })
  if (response.status === 204) return null
  const payload = await response.json().catch(() => ({}))
  if (!response.ok) throw new Error(payload.error || 'Something went wrong. Please try again.')
  return payload
}
const icons = { Overview: '◫', Appointments: '▦', 'My records': '▤', 'My profile': '♙', 'My availability': '◷', 'Patient records': '▧', 'User management': '♙', Settings: '⚙' }
const formatDate = value => new Date(value).toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' })
const formatTime = value => new Date(value).toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })
const friendlyRole = role => ({ ADMIN: 'Administrator', PROFESSIONAL: 'Healthcare professional', PATIENT: 'Patient' })[role] || role

export default function App() {
  const [user, setUser] = useState(null), [view, setView] = useState('Overview'), [loading, setLoading] = useState(true)
  const [toast, setToast] = useState(''), [error, setError] = useState(''), [data, setData] = useState({ appointments: [], professionals: [], records: [], slots: [], users: [], settings: {}, analytics: {} })
  const [authMode, setAuthMode] = useState('login')
  const notify = message => { setToast(message); window.setTimeout(() => setToast(''), 3200) }
  const reportError = message => { setError(message); window.setTimeout(() => setError(''), 4500) }
  const refresh = useCallback(async current => {
    if (!current) return
    try {
      const requests = [api('/appointments'), api('/professionals')]
      if (current.role === 'PATIENT') requests.push(api('/records'))
      if (current.role === 'PROFESSIONAL') requests.push(api('/availability'))
      if (current.role === 'ADMIN') requests.push(api('/admin/users'), api('/admin/settings'), api('/admin/analytics'))
      const result = await Promise.all(requests)
      const next = { appointments: result[0], professionals: result[1] }
      if (current.role === 'PATIENT') next.records = result[2]
      if (current.role === 'PROFESSIONAL') next.slots = result[2]
      if (current.role === 'ADMIN') { next.users = result[2]; next.settings = result[3]; next.analytics = result[4] }
      setData(prev => ({ ...prev, ...next }))
    } catch (e) { reportError(e.message) }
  }, [])
  useEffect(() => { api('/auth/me').then(async current => { setUser(current); await refresh(current) }).catch(() => {}).finally(() => setLoading(false)) }, [refresh])
  const nav = useMemo(() => {
    if (!user) return []
    if (user.role === 'PATIENT') return ['Overview', 'Appointments', 'My records', 'My profile']
    if (user.role === 'PROFESSIONAL') return ['Overview', 'Appointments', 'My availability', 'Patient records']
    return ['Overview', 'Appointments', 'User management', 'Settings']
  }, [user])
  async function signIn(form) {
    try { const current = await api(form.mode === 'register' ? '/auth/register' : '/auth/login', { method: 'POST', body: JSON.stringify(form.mode === 'register' ? { name: form.name, email: form.email, password: form.password } : { email: form.email, password: form.password }) }); setUser(current); await refresh(current); setView('Overview'); notify(`Welcome${current.name ? `, ${current.name.split(' ')[0]}` : ''}`) }
    catch (e) { reportError(e.message) }
  }
  async function signOut() { try { await api('/auth/logout', { method: 'POST' }) } catch {} setUser(null); setData({ appointments: [], professionals: [], records: [], slots: [], users: [], settings: {}, analytics: {} }); setAuthMode('login') }
  async function action(work, success) { try { await work(); if (user) await refresh(user); notify(success) } catch (e) { reportError(e.message) } }
  if (loading) return <div className="loading-screen"><div className="brand-mark">✳</div><span>Preparing your care space…</span></div>
  if (!user) return <AuthScreen mode={authMode} setMode={setAuthMode} onSubmit={signIn} error={error} />
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark">✳</div><div><b>carewell</b><small>HEALTH & WELLNESS</small></div></div>
      <div className="side-label">WORKSPACE</div>
      <nav>{nav.map(item => <button key={item} className={`nav-item ${view === item ? 'active' : ''}`} onClick={() => setView(item)}><span className="nav-icon">{icons[item]}</span>{item}{item === 'Appointments' && data.appointments.filter(a => a.status === 'BOOKED').length > 0 && <span className="nav-count">{data.appointments.filter(a => a.status === 'BOOKED').length}</span>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="help-card"><span className="help-spark">✦</span><b>Here for your health</b><p>Your care, organized in one calm place.</p></div><button className="profile-mini" onClick={signOut}><div className="avatar">{user.name?.split(' ').map(x => x[0]).slice(0, 2).join('')}</div><div className="profile-text"><b>{user.name}</b><small>{friendlyRole(user.role)}</small></div><span className="logout">↪</span></button></div>
    </aside>
    <main className="main-area">
      <header className="topbar"><div className="crumb">Carewell <span>/</span> <b>{view}</b></div><div className="top-actions"><span className="today-label">{new Date().toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })}</span><div className="avatar small">{user.name?.split(' ').map(x => x[0]).slice(0, 2).join('')}</div></div></header>
      <div className="page-content"><div className="page-heading"><div><div className="eyebrow">{user.role === 'PATIENT' ? 'YOUR CARE, AT A GLANCE' : user.role === 'ADMIN' ? 'PLATFORM OVERVIEW' : 'YOUR PRACTICE'}</div><h1>{view === 'Overview' ? `Good ${new Date().getHours() < 12 ? 'morning' : new Date().getHours() < 18 ? 'afternoon' : 'evening'}, ${user.name?.split(' ')[0]}` : view}</h1><p>{view === 'Overview' ? 'Here’s what’s happening with your health today.' : pageDescription(view, user.role)}</p></div><div className="heading-mark">✳</div></div>
        {view === 'Overview' && <Overview user={user} data={data} setView={setView} action={action} />}
        {view === 'Appointments' && <Appointments user={user} data={data} action={action} />}
        {view === 'My availability' && <Availability data={data} action={action} />}
        {view === 'My records' && <Records user={user} data={data} action={action} />}
        {view === 'My profile' && <Profile user={user} onUpdated={setUser} notify={notify} reportError={reportError} />}
        {view === 'Patient records' && <ProfessionalRecords data={data} action={action} />}
        {view === 'User management' && <Users data={data} action={action} />}
        {view === 'Settings' && <Settings data={data} action={action} />}
      </div>
    </main>
    {toast && <div className="toast success"><span>✓</span>{toast}</div>}{error && <div className="toast error"><span>!</span>{error}</div>}
  </div>
}

function pageDescription(view, role) {
  return ({ 'Appointments': 'Manage bookings and stay up to date with every visit.', 'My availability': 'Set the hours patients can book with you.', 'My records': 'Your personal health history, kept together.', 'My profile': 'Keep your contact information up to date.', 'Patient records': 'Review health records for patients in your care.', 'User management': 'Manage people and roles across your platform.', 'Settings': 'Configure your clinic experience.' })[view] || (role === 'PATIENT' ? 'Your care, organized.' : 'A clearer view of care.')
}

function AuthScreen({ mode, setMode, onSubmit, error }) {
  const [form, setForm] = useState({ name: '', email: '', password: '' }), [busy, setBusy] = useState(false)
  const submit = async e => { e.preventDefault(); setBusy(true); await onSubmit({ ...form, mode }); setBusy(false) }
  return <div className="auth-layout"><div className="auth-art"><div className="brand light"><div className="brand-mark">✳</div><div><b>carewell</b><small>HEALTH & WELLNESS</small></div></div><div className="art-copy"><span className="eyebrow">CARE THAT MEETS YOU HERE</span><h1>A healthier life,<br/><em>within reach.</em></h1><p>Appointments, trusted advice, and your health story — all in one thoughtful place.</p></div><div className="art-bottom"><div className="orbit orbit-one"></div><div className="orbit orbit-two"></div><div className="orbit-center">✳</div><div className="art-caption">Your health journey, thoughtfully supported.</div></div></div>
    <div className="auth-panel"><div className="auth-form-wrap"><div className="mobile-brand"><span className="brand-mark">✳</span><b>carewell</b></div><span className="eyebrow">{mode === 'login' ? 'WELCOME BACK' : 'GET STARTED'}</span><h2>{mode === 'login' ? 'Sign in to Carewell' : 'Create your account'}</h2><p className="auth-sub">{mode === 'login' ? 'Your care space is ready when you are.' : 'Start managing your health in one place.'}</p>
      {error && <div className="inline-error">{error}</div>}
      <form onSubmit={submit} className="form-stack">{mode === 'register' && <label>Full name<input required maxLength="120" placeholder="Your name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}/></label>}<label>Email address<input type="email" required placeholder="you@example.com" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/></label><label>Password<input type="password" minLength="8" required placeholder="At least 8 characters" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })}/></label><button className="button primary full" disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create patient account'} <span>→</span></button></form>
      <div className="auth-switch">{mode === 'login' ? <>New to Carewell? <button onClick={() => setMode('register')}>Create an account</button></> : <>Already have an account? <button onClick={() => setMode('login')}>Sign in</button></>}</div>
      {mode === 'login' && <div className="demo-box"><div className="demo-title"><span>✦</span> DEMO ACCESS</div><p>Explore the workspace with a sample account</p><div className="demo-accounts"><button onClick={() => setForm({ email: 'patient@carewell.test', password: 'Patient123!', name: '' })}><b>Patient</b><span>patient@carewell.test</span></button><button onClick={() => setForm({ email: 'doctor@carewell.test', password: 'Doctor123!', name: '' })}><b>Professional</b><span>doctor@carewell.test</span></button><button onClick={() => setForm({ email: 'admin@carewell.test', password: 'Admin123!', name: '' })}><b>Admin</b><span>admin@carewell.test</span></button></div><small>Click an account to fill its demo credentials. Passwords are shown in the project README.</small></div>}
    </div><div className="auth-footer">© 2026 Carewell Health <span>Private · Secure · Connected</span></div></div></div>
}

function Overview({ user, data, setView, action }) {
  const upcoming = data.appointments.filter(a => a.status === 'BOOKED').sort((a,b) => new Date(a.slot.startsAt)-new Date(b.slot.startsAt))
  if (user.role === 'ADMIN') return <><div className="stats-grid">{[['Total users',data.analytics.users,'♙','tint-blue'],['Patients',data.analytics.patients,'♡','tint-rose'],['Professionals',data.analytics.professionals,'✚','tint-green'],['Appointments',data.analytics.appointments,'▦','tint-lilac']].map(([title,value,icon,color])=><Stat key={title} title={title} value={value ?? 0} icon={icon} color={color}/>)}</div><div className="dashboard-grid"><section className="card wide-card"><CardTitle title="Recent appointments" action="View all" onClick={() => setView('Appointments')}/><AppointmentList appointments={upcoming.slice(0,5)} role={user.role}/></section><section className="card insight-card"><div className="insight-icon">✦</div><div className="eyebrow">CAREWELL INSIGHTS</div><h3>Your platform<br/>at a glance</h3><p>{data.analytics.upcoming || 0} upcoming visits are on the calendar. Keep your community connected and care running smoothly.</p><div className="insight-footer"><span className="tiny-dot"></span>{data.analytics.completed || 0} visits completed</div></section></div></>
  const isPatient=user.role==='PATIENT';
  return <><div className="welcome-banner"><div className="welcome-orb">{isPatient?'♡':'✚'}</div><div><span className="eyebrow">{isPatient?'YOUR NEXT STEP':'TODAY IN YOUR PRACTICE'}</span><h2>{isPatient ? upcoming.length ? 'Your next visit is on the calendar.' : 'Let’s make time for your health.' : `${upcoming.length} upcoming ${upcoming.length === 1 ? 'visit' : 'visits'} to prepare for.`}</h2><p>{isPatient ? 'Book with a care professional when you’re ready.' : 'A little preparation makes every visit count.'}</p></div>{isPatient&&<button className="button light-button" onClick={() => setView('Appointments')}>Book a visit <span>→</span></button>}</div>
    <div className="stats-grid compact-stats"><Stat title="Upcoming visits" value={upcoming.length} icon="▦" color="tint-blue"/><Stat title={isPatient?'Health records':'Completed visits'} value={isPatient?data.records.length:data.appointments.filter(a=>a.status==='COMPLETED').length} icon="▤" color="tint-green"/><Stat title="Care professional" value={isPatient?data.professionals.length:1} icon="✚" color="tint-rose"/></div>
    <div className="dashboard-grid"><section className="card wide-card"><CardTitle title={isPatient?'Your upcoming visits':'Your schedule'} action="See all" onClick={() => setView('Appointments')}/><AppointmentList appointments={upcoming.slice(0,4)} role={user.role}/></section><section className="card side-card"><CardTitle title={isPatient?'Your care team':'Quick actions'}/>{isPatient ? data.professionals.slice(0,3).map(p=><div className="doctor-row" key={p.id}><div className="doctor-avatar">{p.name.split(' ').map(x=>x[0]).slice(-2).join('')}</div><div><b>{p.name}</b><small>{p.specialty || 'Healthcare professional'}</small></div><span className="online-dot"></span></div>) : <div className="quick-actions"><button onClick={()=>setView('My availability')}><span>◷</span><div><b>Update availability</b><small>Set your bookable hours</small></div><i>→</i></button><button onClick={()=>setView('Patient records')}><span>▧</span><div><b>Review patient records</b><small>Continue a patient’s care</small></div><i>→</i></button></div>}{isPatient&&<button className="text-button" onClick={()=>setView('Appointments')}>Browse appointments →</button>}</section></div>
  </>
}

function Stat({title,value,icon,color}) { return <div className="stat-card"><div className={`stat-icon ${color}`}>{icon}</div><div><small>{title}</small><strong>{value}</strong></div><span className="stat-more">↗</span></div> }
function CardTitle({title,action,onClick}) { return <div className="card-title"><h3>{title}</h3>{action&&<button className="text-button" onClick={onClick}>{action} <span>→</span></button>}</div> }
function Empty({title,copy,action,label}) { return <div className="empty-state"><div className="empty-icon">✳</div><b>{title}</b><p>{copy}</p>{action&&<button className="button secondary" onClick={action}>{label} →</button>}</div> }
function AppointmentList({appointments,role,action}) { if(!appointments?.length)return <Empty title="Nothing on the calendar yet" copy="When a visit is booked, it will appear here."/>; return <div className="appointment-list">{appointments.map(a=><AppointmentRow key={a.id} appointment={a} role={role} action={action}/>)}</div> }
function AppointmentRow({appointment:a,role,action}) {
  const other=role==='PATIENT'?a.professional:a.patient, [open,setOpen]=useState(false), [form,setForm]=useState({advice:a.advice||'',summary:a.summary||''})
  return <div className="appointment-entry"><div className="appointment-row"><div className="date-block"><b>{new Date(a.slot.startsAt).toLocaleDateString(undefined,{day:'2-digit'})}</b><small>{new Date(a.slot.startsAt).toLocaleDateString(undefined,{month:'short'})}</small></div><div className="appointment-main"><b>{other?.name}</b><small>{other?.specialty || (role==='PATIENT'?'Healthcare professional':'Patient')} · {formatTime(a.slot.startsAt)}</small></div><span className={`status-pill ${a.status.toLowerCase()}`}>{a.status.toLowerCase()}</span><span className="row-arrow">›</span></div>{a.status==='COMPLETED'&&role==='PATIENT'&&a.advice&&<div className="advice-preview"><b>Medical advice</b><p>{a.advice}</p>{a.summary&&<small>{a.summary}</small>}</div>}{action&&a.status==='BOOKED'&&role==='PROFESSIONAL'&&<div className="appointment-tools"><button className="text-button" onClick={()=>setOpen(!open)}>{open?'Close consultation':'Record consultation'} ↓</button><button className="text-button danger-text" onClick={()=>action(()=>api(`/appointments/${a.id}/status`,{method:'PATCH',body:JSON.stringify({status:'CANCELLED'})}),'Appointment cancelled')}>Cancel</button></div>}{open&&<form className="record-form consultation-form" onSubmit={e=>{e.preventDefault();action(()=>api(`/appointments/${a.id}/consultation`,{method:'PATCH',body:JSON.stringify(form)}),'Consultation saved');setOpen(false)}}><label>Medical advice<textarea required rows="3" maxLength="8000" value={form.advice} onChange={e=>setForm({...form,advice:e.target.value})} placeholder="Write advice for the patient"/></label><label>Consultation summary<textarea rows="2" maxLength="4000" value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})} placeholder="Add a brief visit summary"/></label><button className="button primary">Save and complete visit</button></form>}{action&&role==='ADMIN'&&<div className="appointment-tools"><span>Manage status</span>{['BOOKED','COMPLETED','CANCELLED'].map(status=><button key={status} className={`status-action ${a.status===status?'selected':''}`} onClick={()=>action(()=>api(`/appointments/${a.id}/status`,{method:'PATCH',body:JSON.stringify({status})}),`Appointment marked ${status.toLowerCase()}`)}>{status.toLowerCase()}</button>)}</div>}</div>
}

function Appointments({user,data,action}) {
  const [professionalId,setProfessionalId]=useState(''), [slots,setSlots]=useState([]), [reason,setReason]=useState(''), [selected,setSelected]=useState('')
  const patients=user.role==='PATIENT'
  useEffect(()=>{if(patients&&data.professionals.length&&!professionalId)setProfessionalId(String(data.professionals[0].id))},[patients,data.professionals,professionalId])
  useEffect(()=>{if(patients&&professionalId)api(`/professionals/${professionalId}/availability`).then(setSlots).catch(e=>{})},[patients,professionalId,data.appointments.length])
  const grouped=useMemo(()=>{const map={};slots.forEach(s=>{const day=formatDate(s.startsAt);(map[day] ||= []).push(s)});return map},[slots])
  return <div className="content-stack">{patients&&<section className="card booking-card"><div className="booking-heading"><div className="booking-icon">＋</div><div><h3>Book a consultation</h3><p>Choose a professional and a time that works for you.</p></div></div><div className="booking-controls"><label>Healthcare professional<select value={professionalId} onChange={e=>{setProfessionalId(e.target.value);setSelected('')}}><option value="">Select a professional</option>{data.professionals.map(p=><option value={p.id} key={p.id}>{p.name} · {p.specialty || 'General care'}</option>)}</select></label><label>Reason for visit <input maxLength="2000" placeholder="What would you like help with? (optional)" value={reason} onChange={e=>setReason(e.target.value)}/></label></div><div className="slot-heading"><b>Available times</b><span>{slots.length} open {slots.length===1?'time':'times'}</span></div>{Object.keys(grouped).length ? <div className="slot-days">{Object.entries(grouped).map(([day,daySlots])=><div className="slot-day" key={day}><b>{day}</b><div>{daySlots.map(slot=><button className={`slot-chip ${String(selected)===String(slot.id)?'chosen':''}`} key={slot.id} onClick={()=>setSelected(String(slot.id))}>{formatTime(slot.startsAt)}</button>)}</div></div>)}</div>:<p className="muted-note">No times are currently available. Please check back soon.</p>}<div className="booking-footer"><span>Appointments are scheduled in your local time.</span><button className="button primary" disabled={!selected} onClick={()=>action(()=>api('/appointments',{method:'POST',body:JSON.stringify({availabilityId:Number(selected),reason})}),'Appointment booked successfully')}>Confirm booking <span>→</span></button></div></section>}
    <section className="card"><CardTitle title={patients?'Your appointments':user.role==='ADMIN'?'All appointments':'Your consultations'}/><AppointmentList appointments={data.appointments} role={user.role} action={action}/></section></div>
}

function Availability({data,action}) {
  const [form,setForm]=useState({startsAt:'',endsAt:''})
  return <div className="content-stack"><section className="card"><CardTitle title="Add availability"/><p className="card-intro">Choose a start and end time. Patients can book any open time slot.</p><form className="inline-form" onSubmit={e=>{e.preventDefault();action(()=>api('/availability',{method:'POST',body:JSON.stringify(form)}),'Availability added');setForm({startsAt:'',endsAt:''})}}><label>Starts<input type="datetime-local" required value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></label><label>Ends<input type="datetime-local" required value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></label><button className="button primary">Add time <span>＋</span></button></form></section><section className="card"><CardTitle title="Your availability"/><div className="table-wrap"><table><thead><tr><th>DATE & TIME</th><th>STATUS</th><th></th></tr></thead><tbody>{data.slots.filter(s=>new Date(s.startsAt)>new Date()).map(s=><tr key={s.id}><td><b>{formatDate(s.startsAt)}</b><small>{formatTime(s.startsAt)} – {formatTime(s.endsAt)}</small></td><td><span className={`status-pill ${s.booked?'booked':'available'}`}>{s.booked?'Booked':'Available'}</span></td><td>{!s.booked&&<button className="icon-button" title="Remove availability" onClick={()=>action(()=>api(`/availability/${s.id}`,{method:'DELETE'}),'Availability removed')}>×</button>}</td></tr>)}</tbody></table>{!data.slots.filter(s=>new Date(s.startsAt)>new Date()).length&&<Empty title="No upcoming availability" copy="Add your first time slot so patients can book with you."/>}</div></section></div>
}

function Records({user,data,action}) {
  const [show,setShow]=useState(false),[form,setForm]=useState({title:'',details:''})
  return <div className="content-stack"><section className="card records-card"><CardTitle title="Your health records" action={user.role==='PATIENT'?(show?'Cancel':'Add a record'):undefined} onClick={()=>setShow(!show)}/><p className="card-intro">Keep important health information in one place for your care team.</p>{show&&<form className="record-form" onSubmit={e=>{e.preventDefault();action(()=>api('/records',{method:'POST',body:JSON.stringify(form)}),'Health record saved');setForm({title:'',details:''});setShow(false)}}><label>Record title<input required maxLength="180" placeholder="e.g. Medication, allergy, or health history" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Details<textarea rows="4" maxLength="5000" placeholder="Add relevant details" value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/></label><button className="button primary">Save record</button></form>}{data.records.length?<div className="record-list">{data.records.map(r=><article className="record-item" key={r.id}><div className="record-icon">▤</div><div><b>{r.title}</b><p>{r.details || 'No additional details.'}</p><small>Updated {formatDate(r.updatedAt)} · Added by {r.author}</small></div></article>)}</div>:<Empty title="Your health story starts here" copy="Add a record to keep personal health details close at hand." action={()=>setShow(true)} label="Add a health record"/>}</section></div>
}

function Profile({user,onUpdated,notify,reportError}) {
  const [form,setForm]=useState({name:user.name||'',email:user.email||'',phone:user.phone||''}),[saving,setSaving]=useState(false)
  return <section className="card profile-card"><CardTitle title="Personal information"/><p className="card-intro">This information helps your care team keep in touch.</p><form className="form-stack profile-form" onSubmit={async e=>{e.preventDefault();setSaving(true);try{const updated=await api('/auth/profile',{method:'PUT',body:JSON.stringify(form)});onUpdated(updated);notify('Profile updated')}catch(err){reportError(err.message)}finally{setSaving(false)}}}><label>Full name<input required maxLength="120" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email address<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Phone number<input type="tel" maxLength="40" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Optional"/></label><button className="button primary" disabled={saving}>{saving?'Saving…':'Save profile'} <span>→</span></button></form></section>
}

function ProfessionalRecords({data,action}) {
  const [patientId,setPatientId]=useState(''),[records,setRecords]=useState([]),[form,setForm]=useState({title:'',details:''})
  const patients=[...new Map(data.appointments.map(a=>[a.patient.id,a.patient])).values()]
  useEffect(()=>{if(patientId)api(`/records?patientId=${patientId}`).then(setRecords).catch(()=>setRecords([]));else setRecords([])},[patientId,data.appointments.length])
  return <div className="content-stack"><section className="card"><CardTitle title="Patient health records"/><p className="card-intro">Records are available only for patients with an appointment in your care.</p><label className="select-patient">Select a patient<select value={patientId} onChange={e=>setPatientId(e.target.value)}><option value="">Choose patient</option>{patients.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{patientId&&<><div className="record-list">{records.map(r=><article className="record-item" key={r.id}><div className="record-icon">▤</div><div><b>{r.title}</b><p>{r.details||'No additional details.'}</p><small>Updated {formatDate(r.updatedAt)} · Added by {r.author}</small></div></article>)}</div>{!records.length&&<div className="muted-note">No health records have been added yet.</div>}<form className="record-form pro-record-form" onSubmit={async e=>{e.preventDefault();await action(()=>api(`/records?patientId=${patientId}`,{method:'POST',body:JSON.stringify(form)}),'Patient record saved');setRecords(await api(`/records?patientId=${patientId}`));setForm({title:'',details:''})}}><h4>Add a care note</h4><label>Title<input required maxLength="180" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Details<textarea rows="3" maxLength="5000" value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/></label><button className="button primary">Save care note</button></form></>}</section></div>
}

function Users({data,action}) {
  const blank={name:'',email:'',role:'PATIENT',specialty:'',phone:'',password:''},[form,setForm]=useState(blank),[editing,setEditing]=useState(null)
  const save=e=>{e.preventDefault();action(()=>api(editing?`/admin/users/${editing}`:'/admin/users',{method:editing?'PUT':'POST',body:JSON.stringify({name:form.name,email:form.email,role:form.role,specialty:form.specialty,phone:form.phone,password:form.password})}),editing?'User updated':'User created');setForm(blank);setEditing(null)}
  return <div className="content-stack"><section className="card"><CardTitle title={editing?`Edit ${editing}`:'Add a user'}/><form className="user-form" onSubmit={save}><label>Full name<input required maxLength="120" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email address<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Role<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="PATIENT">Patient</option><option value="PROFESSIONAL">Healthcare professional</option><option value="ADMIN">Admin</option></select></label><label>Specialty<input value={form.specialty} onChange={e=>setForm({...form,specialty:e.target.value})} placeholder="For professionals"/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label>{editing?'New password (optional)':'Temporary password'}<input type="password" minLength="8" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><div className="form-actions"><button className="button primary">{editing?'Save changes':'Create account'}</button>{editing&&<button type="button" className="button secondary" onClick={()=>{setEditing(null);setForm(blank)}}>Cancel</button>}</div></form></section><section className="card"><CardTitle title="Platform users"/><div className="table-wrap"><table><thead><tr><th>NAME</th><th>ROLE</th><th>EMAIL</th><th></th></tr></thead><tbody>{data.users.map(u=><tr key={u.id}><td><div className="user-cell"><span className="avatar table-avatar">{u.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><div><b>{u.name}</b><small>{u.specialty||u.phone||'Carewell member'}</small></div></div></td><td><span className={`role-tag ${u.role.toLowerCase()}`}>{friendlyRole(u.role)}</span></td><td>{u.email}</td><td><div className="row-actions"><button className="text-button" onClick={()=>{setEditing(u.id);setForm({...u,password:''})}}>Edit</button><button className="text-button danger-text" onClick={()=>action(()=>api(`/admin/users/${u.id}`,{method:'DELETE'}),'User removed')}>Remove</button></div></td></tr>)}</tbody></table></div></section></div>
}

function Settings({data,action}) {
  const [form,setForm]=useState(data.settings)
  useEffect(()=>setForm(data.settings),[data.settings])
  return <div className="settings-layout"><section className="card settings-card"><CardTitle title="Clinic settings"/><p className="card-intro">These details shape how Carewell works for your community.</p><form className="form-stack settings-form" onSubmit={e=>{e.preventDefault();action(()=>api('/admin/settings',{method:'PUT',body:JSON.stringify(form)}),'Settings saved')}}><label>Clinic name<input value={form.clinicName||''} onChange={e=>setForm({...form,clinicName:e.target.value})}/></label><label>Default appointment length<select value={form.appointmentDurationMinutes||'60'} onChange={e=>setForm({...form,appointmentDurationMinutes:e.target.value})}><option value="30">30 minutes</option><option value="45">45 minutes</option><option value="60">60 minutes</option><option value="90">90 minutes</option></select></label><label>Booking window (days)<input type="number" min="1" max="365" value={form.bookingWindowDays||'60'} onChange={e=>setForm({...form,bookingWindowDays:e.target.value})}/></label><div className="setting-note"><span>ⓘ</span><p>Changes apply to future scheduling across the platform.</p></div><button className="button primary">Save settings <span>→</span></button></form></section><section className="card settings-side"><div className="insight-icon">✦</div><h3>Carewell<br/>at a glance</h3><p>Understand the heartbeat of your platform.</p><div className="mini-metric"><span>Upcoming appointments</span><b>{data.analytics.upcoming||0}</b></div><div className="mini-metric"><span>Completed consultations</span><b>{data.analytics.completed||0}</b></div><div className="mini-metric"><span>Active care professionals</span><b>{data.analytics.professionals||0}</b></div></section></div>
}
